### ISSUE TITLE
多平台备份

### ISSUE THREAD

**Issue by bennyzdog** [tgbot-collection/archiver#2]
目前只是备份网页到 web.archive.org，由于它的抓取策略，有些内容是无法备份的

希望能同时备份到 archive.today，或者其它备份平台，甚至直接爬取返回 mhtml

**Comment by BennyThink** [comment]
won't fix due to cf captcha

![telegram-cloud-photo-size-5-6257819680609776316-y](https://user-images.githubusercontent.com/14024832/180595347-836ceb21-b01c-4b39-bedd-6103d3d77d5c.jpg)
