### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Ashrafmdmatin41** [tgbot-collection/archiver#28]
{
  "error": {
    "code": 403,
    "message": "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.",
    "status": "PERMISSION_DENIED"
  }
}

>> make it to deploy on heroku

**Comment by BennyThink** [comment]
No time for heroku support.

**Comment by Ashrafmdmatin41** [comment]
> No time for heroku support.

Ok
