### ISSUE TITLE
Underscore in URLs

### ISSUE THREAD

**Issue by kachkaev** [tgbot-collection/archiver#6]
👋 @BennyThink, great bot 🤩

I noticed a small issue with underscores in URLs and decided to share. They are treated as the control character for italics and this breaks the markup. Here is an example:

<img alt="Screenshot 2022-08-20 at 17 10 12" src="https://user-images.githubusercontent.com/608862/185756208-8dda8eaf-ff2d-472a-9f91-88aa19a06e91.png">

As you can see, https://en.wikipedia.org/wiki/Main_Page becomes https://en.wikipedia.org/wiki/MainPage and https://web.archive.org/web/20220820154818/https://en.wikipedia.org/wiki/Main_Page turns into
https://web.archive.org/web/20220820154818/https://en.wikipedia.org/wiki/MainPage.

Hope that this is fixable and thanks for this handy bot again!

**Comment by BennyThink** [comment]
Thanks for sharing. Will fix later

**Comment by BennyThink** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/14024832/186935780-1418d56e-7971-46a2-91fa-ec699e58d781.png">


fixed!
